openapi: 3.1.0
info:
  version: 1.0.0
  title: odinbook API
  contact:
    name: Isutomu Naruto
    email: isutomu@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: auth
    description: Authentication and authorization operations.
  - name: post
    description: CRUD operations with post(s).
servers:
  - url: http://localhost:5173
    description: Localhost Development Server
  - url: https://odin-book-backend-top-production.up.railway.app
    description: Production Server
paths:
  /auth/signup:
    post:
      summary: Signup an user
      operationId: signup
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: Created User
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
          headers:
            Set-Cookie:
              schema:
                type: string
                example: connect.sid=abcde12345; Path=/; Expires=Wed, 01 Apr 1990 20:20:20 GMT;
                  HttpOnly
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        "422":
          description: Unprocessable Content
          content:
            application/json:
              schema:
                $ref: "#/paths/~1auth~1signup/post/responses/409/content/application~1json/sche\
                  ma"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/paths/~1auth~1signup/post/responses/409/content/application~1json/sche\
                  ma"
  /auth/login:
    post:
      summary: Login an user
      operationId: login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  $ref: "#/paths/~1auth~1signup/post/requestBody/content/application~1json/schema\
                    /properties/username"
                password:
                  $ref: "#/paths/~1auth~1signup/post/requestBody/content/application~1json/schema\
                    /properties/password"
      responses:
        "200":
          description: Logged in user
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
          headers:
            Set-Cookie:
              schema:
                type: string
                example: connect.sid=abcde12345; Path=/; Expires=Wed, 01 Apr 1990 20:20:20 GMT;
                  HttpOnly
        "422":
          $ref: "#/paths/~1auth~1signup/post/responses/422"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  /auth/verify-session:
    get:
      summary: Verify is user session is valid
      operationId: verify-session
      tags:
        - auth
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Session is valid
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/paths/~1auth~1signup/post/responses/409/content/application~1json/sche\
                  ma"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  /post/create:
    post:
      summary: Create a post
      operationId: createPost
      tags:
        - post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
      responses:
        "201":
          description: Created post
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        "422":
          $ref: "#/paths/~1auth~1signup/post/responses/422"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  "/post/delete/{postId}":
    delete:
      summary: Delete a post
      operationId: deletePost
      tags:
        - post
      parameters:
        - in: path
          name: postId
          schema:
            type: string
          required: true
          description: ID of the post to delete
      responses:
        "204":
          description: Deleted post
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/paths/~1auth~1signup/post/responses/409/content/application~1json/sche\
                  ma"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  "/post/update/{postId}":
    patch:
      summary: Update a post content
      operationId: updatePost
      tags:
        - post
      parameters:
        - in: path
          name: postId
          schema:
            type: string
          required: true
          description: ID of the post to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  $ref: "#/paths/~1post~1create/post/requestBody/content/application~1json/schema\
                    /properties/content"
      responses:
        "204":
          description: Updated post
        "404":
          $ref: "#/paths/~1post~1delete~1%7BpostId%7D/delete/responses/404"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  /post/feed:
    get:
      summary: Get an user feed
      operationId: getFeed
      tags:
        - post
      responses:
        "200":
          description: Got feed
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - data
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/paths/~1post~1read~1%7BpostId%7D/get/responses/200/content/application\
                        ~1json/schema/properties/data"
                    maxItems: 10
                    uniqueItems: true
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  "/post/feed/pagination/{lastPostId}":
    get:
      summary: Get more posts from an user feed
      operationId: getFeedPagination
      tags:
        - post
      parameters:
        - in: path
          name: lastPostId
          schema:
            type: string
          required: true
          description: ID of the last post of the current feed on the frontend
      responses:
        "200":
          description: Got more posts of feed
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - data
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/paths/~1post~1feed/get/responses/200/content/application~1json/schema/\
                      properties/data"
        "404":
          $ref: "#/paths/~1post~1delete~1%7BpostId%7D/delete/responses/404"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  "/post/read/{postId}":
    get:
      summary: Get a post
      operationId: getPost
      tags:
        - post
      parameters:
        - in: path
          name: postId
          schema:
            type: string
          required: true
          description: ID of the post
      responses:
        "200":
          description: Got post
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - data
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      content:
                        type: string
                      publishedAt:
                        type: string
                        format: date-time
                      updatedAt:
                        type:
                          - string
                          - null
                        format: date-time
                      author:
                        type: object
                        properties:
                          username:
                            type: string
        "404":
          $ref: "#/paths/~1post~1delete~1%7BpostId%7D/delete/responses/404"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  "/post/read-all/{username}":
    get:
      summary: Get all posts from an user
      operationId: getAllPosts
      tags:
        - post
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: username
      responses:
        "200":
          description: Got user's posts
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - data
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/paths/~1post~1feed/get/responses/200/content/application~1json/schema/\
                      properties/data"
        "404":
          $ref: "#/paths/~1post~1delete~1%7BpostId%7D/delete/responses/404"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
  "/post/read-all/{username}/pagination/{lastPostId}":
    get:
      summary: Get more posts from an user
      operationId: getAllPostsPagination
      tags:
        - post
      parameters:
        - in: path
          name: username
          schema:
            type: string
          required: true
          description: username
        - in: path
          name: lastPostId
          schema:
            type: string
          required: true
          description: ID of the last post of the current feed on the frontend
      responses:
        "200":
          description: Got user's posts
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - data
                properties:
                  message:
                    type: string
                  data:
                    $ref: "#/paths/~1post~1feed/get/responses/200/content/application~1json/schema/\
                      properties/data"
        "404":
          $ref: "#/paths/~1post~1delete~1%7BpostId%7D/delete/responses/404"
        "500":
          $ref: "#/paths/~1auth~1signup/post/responses/500"
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
