openapi:  3.2.0
info:
  version: 1.0.0
  title: odinbook API
  contact:
    name: Isutomu Naruto
    email: isutomu@gmail.com
  description: This is the API definition for the odinbook API.

  tags:
    - name: Auth
      description: Authentication and authorization operations.

  servers:
    - url: 'http://localhost:{port}'
      description: Localhost Development Server
      variables:
        port:
          default: '3000'
          enum:
            - '8000'
            - '3000'
    - url: 'https://odin-book-backend-top-production.up.railway.app'
      description: Production Server
  
  paths:
    /auth/signup:
      $ref: 'paths/auth/signup.yaml'
    /auth/login:
      $ref: 'paths/auth/login.yaml'

  security:
    - cookieAuth: []

  components:
    securitySchemes:
      coookieAuth:
        type: apiKey
        in: cookie
        name: 'connect.sid'